version: 1.0.{build}
configuration: Debug
platform: Any CPU
build:
  publish_wap_xcopy: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  parallel: true
  verbosity: detailed
artifacts:
- path: release
  name: jsil